# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tokki_pb2 as tokki__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tokki_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Main service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/tokki.AgentService/Execute',
                request_serializer=tokki__pb2.Request.SerializeToString,
                response_deserializer=tokki__pb2.Delta.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/tokki.AgentService/Stream',
                request_serializer=tokki__pb2.Request.SerializeToString,
                response_deserializer=tokki__pb2.Delta.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/tokki.AgentService/Ping',
                request_serializer=tokki__pb2.PingRequest.SerializeToString,
                response_deserializer=tokki__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/tokki.AgentService/GetMetadata',
                request_serializer=tokki__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=tokki__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/tokki.AgentService/ListConversations',
                request_serializer=tokki__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=tokki__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.LoadMessages = channel.unary_unary(
                '/tokki.AgentService/LoadMessages',
                request_serializer=tokki__pb2.LoadMessagesRequest.SerializeToString,
                response_deserializer=tokki__pb2.LoadMessagesResponse.FromString,
                _registered_method=True)
        self.DeleteConversation = channel.unary_unary(
                '/tokki.AgentService/DeleteConversation',
                request_serializer=tokki__pb2.DeleteConversationRequest.SerializeToString,
                response_deserializer=tokki__pb2.DeleteConversationResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Main service definition
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=tokki__pb2.Request.FromString,
                    response_serializer=tokki__pb2.Delta.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=tokki__pb2.Request.FromString,
                    response_serializer=tokki__pb2.Delta.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=tokki__pb2.PingRequest.FromString,
                    response_serializer=tokki__pb2.PingResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=tokki__pb2.GetMetadataRequest.FromString,
                    response_serializer=tokki__pb2.GetMetadataResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=tokki__pb2.ListConversationsRequest.FromString,
                    response_serializer=tokki__pb2.ListConversationsResponse.SerializeToString,
            ),
            'LoadMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadMessages,
                    request_deserializer=tokki__pb2.LoadMessagesRequest.FromString,
                    response_serializer=tokki__pb2.LoadMessagesResponse.SerializeToString,
            ),
            'DeleteConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversation,
                    request_deserializer=tokki__pb2.DeleteConversationRequest.FromString,
                    response_serializer=tokki__pb2.DeleteConversationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tokki.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tokki.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Main service definition
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tokki.AgentService/Execute',
            tokki__pb2.Request.SerializeToString,
            tokki__pb2.Delta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tokki.AgentService/Stream',
            tokki__pb2.Request.SerializeToString,
            tokki__pb2.Delta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokki.AgentService/Ping',
            tokki__pb2.PingRequest.SerializeToString,
            tokki__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokki.AgentService/GetMetadata',
            tokki__pb2.GetMetadataRequest.SerializeToString,
            tokki__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokki.AgentService/ListConversations',
            tokki__pb2.ListConversationsRequest.SerializeToString,
            tokki__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokki.AgentService/LoadMessages',
            tokki__pb2.LoadMessagesRequest.SerializeToString,
            tokki__pb2.LoadMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokki.AgentService/DeleteConversation',
            tokki__pb2.DeleteConversationRequest.SerializeToString,
            tokki__pb2.DeleteConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
